#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libbsd
Version  : 0.8.3
Release  : 11
URL      : http://libbsd.freedesktop.org/releases/libbsd-0.8.3.tar.xz
Source0  : http://libbsd.freedesktop.org/releases/libbsd-0.8.3.tar.xz
Summary  : Utility functions from BSD systems
Group    : Development/Tools
License  : BSD-4-Clause
Requires: libbsd-lib
Requires: libbsd-doc

%description
libbsd - Utility functions from BSD systems
This library provides useful functions commonly found on BSD systems,
and lacking on others like GNU systems, thus making it easier to port
projects with strong BSD origins, without needing to embed the same
code over and over again on each project.

%package dev
Summary: dev components for the libbsd package.
Group: Development
Requires: libbsd-lib
Provides: libbsd-devel

%description dev
dev components for the libbsd package.


%package doc
Summary: doc components for the libbsd package.
Group: Documentation

%description doc
doc components for the libbsd package.


%package lib
Summary: lib components for the libbsd package.
Group: Libraries

%description lib
lib components for the libbsd package.


%prep
%setup -q -n libbsd-0.8.3

%build
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/bsd/bitstring.h
/usr/include/bsd/bsd.h
/usr/include/bsd/err.h
/usr/include/bsd/getopt.h
/usr/include/bsd/libutil.h
/usr/include/bsd/md5.h
/usr/include/bsd/netinet/ip_icmp.h
/usr/include/bsd/nlist.h
/usr/include/bsd/readpassphrase.h
/usr/include/bsd/stdio.h
/usr/include/bsd/stdlib.h
/usr/include/bsd/string.h
/usr/include/bsd/stringlist.h
/usr/include/bsd/sys/bitstring.h
/usr/include/bsd/sys/cdefs.h
/usr/include/bsd/sys/endian.h
/usr/include/bsd/sys/poll.h
/usr/include/bsd/sys/queue.h
/usr/include/bsd/sys/tree.h
/usr/include/bsd/timeconv.h
/usr/include/bsd/unistd.h
/usr/include/bsd/vis.h
/usr/include/bsd/wchar.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man3/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
